spring.application.name=ticket-mania

spring.datasource.url=jdbc:postgresql://localhost:5432/ticket-mania-db
spring.datasource.username=admin
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

api.security.token.private-key=classpath:private_key.pem
api.security.token.public-key=classpath:public_key.pem
stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.secret.webhook=${STRIPE_SECRET_WEBHOOK}